[build]
  base = "client/"
  publish = "client/build"
  command = "npm run build:prod"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  REACT_APP_NODE_ENV = "production"

[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  REACT_APP_NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  REACT_APP_NODE_ENV = "development"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API redirects (if using serverless functions)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS redirect
[[redirects]]
  from = "http://food-delivery-system.netlify.app/*"
  to = "https://food-delivery-system.netlify.app/:splat"
  status = 301
  force = true
